import { CanCommand } from "@/types";

export const CAN_COMMANDS: CanCommand[] = [
  {
    id: "door_open",
    name: "Open doors",
    canId: "201",
    data: "FF 02 FF FF 00 00 00 00",
    description: "Open left and right doors",
  },
  {
    id: "door_close",
    name: "Close doors",
    canId: "201",
    data: "FF 01 FF FF 00 00 00 00",
    description: "Close left and right doors",
  },
  {
    id: "door_stop",
    name: "Stop doors",
    canId: "201",
    data: "FF 03 FF FF 00 00 00 00",
    description: "Stop left and right doors",
  },
  {
    id: "fan_level_0",
    name: "Fan level 0",
    canId: "201",
    data: "00 FF FF FF 00 00 00 00",
    description: "Fan level 0",
  },
  {
    id: "fan_level_1",
    name: "Fan level 1",
    canId: "201",
    data: "01 FF FF FF 00 00 00 00",
    description: "Fan level 1",
  },
  {
    id: "fan_level_2",
    name: "Fan level 2",
    canId: "201",
    data: "02 FF FF FF 00 00 00 00",
    description: "Fan level 2",
  },
  {
    id: "fan_level_3",
    name: "Fan level 3",
    canId: "201",
    data: "03 FF FF FF 00 00 00 00",
    description: "Fan level 3",
  },
  {
    id: "light_mode_1",
    name: "Light mode 1",
    canId: "201",
    data: "FF FF FF 01 00 00 00 00",
    description: "Light strip mode 1",
  },
  {
    id: "light_mode_2",
    name: "Light mode 2",
    canId: "201",
    data: "FF FF FF 02 00 00 00 00",
    description: "Light strip mode 2",
  },
  {
    id: "light_mode_3",
    name: "Light mode 3",
    canId: "201",
    data: "FF FF FF 03 00 00 00 00",
    description: "Light strip mode 3",
  },
  {
    id: "light_mode_4",
    name: "Light mode 4",
    canId: "201",
    data: "FF FF FF 04 00 00 00 00",
    description: "Light strip mode 4",
  },
  {
    id: "start_driving",
    name: "Start driving",
    canId: "200",
    data: "0B B8 FF 07 00 00 00 00",
    description: "Start vehicle driving animation",
  },
  {
    id: "stop_driving",
    name: "Stop driving",
    canId: "200",
    data: "00 00 00 00 00 00 00 00",
    description: "Stop vehicle driving animation",
  },
  {
    id: "suspension_up",
    name: "Raise suspension",
    canId: "201",
    data: "FF FF 01 FF 00 00 00 00",
    description: "Raise vehicle suspension",
  },
  {
    id: "suspension_down",
    name: "Lower suspension",
    canId: "201",
    data: "FF FF 02 FF 00 00 00 00",
    description: "Lower vehicle suspension",
  },
  {
    id: "suspension_stop",
    name: "Stop suspension",
    canId: "201",
    data: "FF FF 03 FF 00 00 00 00",
    description: "Stop vehicle suspension",
  },
];
